development:
  react_cors: true
  database:
    table: asira_lender
    username: asirauser
    password: asirapass
    host: "127.0.0.1"
    port: "5432"
    maxlifetime: 30
    idle_conns: 10
    open_conns: 100
    sslmode: disable
    logmode: true
    timezone: Asia/Jakarta
  kafka:
    host: "10.148.0.3"
    port: "9092"
    user: user
    pass: oRB5KjfuHdXc
    client_id: asira
    sasl: true
    log_verbose: true
    topics:
      produces:
        for_borrower: asira_lender_to_borrower
      consumes:
        for_lender: asira_borrower_to_lender
  clients:
    admin: Z3JhZGlvczp1bHRpbXVz
    react: cmVhY3RrZXk6cmVhY3RwYXNz # reactkey:reactpass
  jwt:
    duration: 10080 # in minutes
    jwt_secret: sXQ8jUMpueOvN5P3cdCR

staging:

production: